name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Released version in SemVer format'
        required: true
        type: string
      prerelease:
        description: 'Prerelease'
        required: false
        type: boolean

jobs:
  linux-x86_64:
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y protobuf-compiler
          sudo apt-get clean

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.91.0

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build
        run: cargo build -r --all-targets --all-features

      - name: Package binaries
        run: tar -czvf signal_client_linux_x86_64.tar.gz ./target/release/signal_client

      - uses: actions/upload-artifact@v4
        with:
          name: signal_client_linux_x86_64.tar.gz
          path: ./signal_client_linux_x86_64.tar.gz

  macos-x86_64:
    runs-on: macos-15-intel
    steps:
      - name: Install dependencies
        run: brew install protobuf

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.91.0

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build
        run: cargo build -r --all-targets --all-features

      - name: Package binaries
        run: tar -czvf signal_client_darwin_x86_64.tar.gz ./target/release/signal_client

      - uses: actions/upload-artifact@v4
        with:
          name: signal_client_darwin_x86_64.tar.gz
          path: ./signal_client_darwin_x86_64.tar.gz

  macos-arm64:
    runs-on: macos-15
    steps:
      - name: Install dependencies
        run: brew install protobuf

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.91.0

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build
        run: cargo build -r --all-targets --all-features

      - name: Package binaries
        run: tar -czvf signal_client_darwin_arm64.tar.gz ./target/release/signal_client

      - uses: actions/upload-artifact@v4
        with:
          name: signal_client_darwin_arm64.tar.gz
          path: ./signal_client_darwin_arm64.tar.gz

  release:
    runs-on: ubuntu-24.04
    needs: [linux-x86_64, macos-x86_64, macos-arm64]
    permissions: 
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v5

      - name: Release Signal client
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ inputs.version }}
          tag_name: v${{ inputs.version }}
          files: ${{ github.workspace }}/**/signal_client*.tar.gz
          generate_release_notes: true
          prerelease: ${{ inputs.prerelease }} 
